// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'src/database/schema.prisma',
  migrations: {
    path: 'src/database/migrations',
    seed: 'ts-node -r tsconfig-paths/register src/database/seed.ts',
  },
  datasource: {
    url: process.env['DIRECT_URL'] || process.env['DATABASE_URL_LOCAL'],
  },
});
